name: Full Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  STACK_ROOT: /tmp/stack-root

jobs:
  build_all_projects:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - name: build all projects
        run: make all
      - name: verify binary exist
        run: |
          test -f kong
          echo "kong binary exists"

  run_all_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - name: run unit tests
        run: make test
      - name: run functional tests
        shell: bash
        run: |
          bash functionnal_tests/install_requirements.sh
          source .venv/bin/activate
          python3 functionnal_tests/run.py
