name: Kong Compiler - Basic Checks

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

env:
  STACK_ROOT: /tmp/stack-root

jobs:
  check_kong_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - name: build Kong compiler
        run: make
      - name: check Kong binary exists
        run: test -f kong
